/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as MomentosRouteImport } from './routes/momentos'
import { Route as HumorRouteImport } from './routes/humor'
import { Route as FilmesRouteImport } from './routes/filmes'
import { Route as DatesRouteImport } from './routes/dates'
import { Route as ClubeDoLivroRouteImport } from './routes/clube-do-livro'
import { Route as CartasRouteImport } from './routes/cartas'
import { Route as IndexRouteImport } from './routes/index'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentosRoute = MomentosRouteImport.update({
  id: '/momentos',
  path: '/momentos',
  getParentRoute: () => rootRouteImport,
} as any)
const HumorRoute = HumorRouteImport.update({
  id: '/humor',
  path: '/humor',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmesRoute = FilmesRouteImport.update({
  id: '/filmes',
  path: '/filmes',
  getParentRoute: () => rootRouteImport,
} as any)
const DatesRoute = DatesRouteImport.update({
  id: '/dates',
  path: '/dates',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubeDoLivroRoute = ClubeDoLivroRouteImport.update({
  id: '/clube-do-livro',
  path: '/clube-do-livro',
  getParentRoute: () => rootRouteImport,
} as any)
const CartasRoute = CartasRouteImport.update({
  id: '/cartas',
  path: '/cartas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cartas': typeof CartasRoute
  '/clube-do-livro': typeof ClubeDoLivroRoute
  '/dates': typeof DatesRoute
  '/filmes': typeof FilmesRoute
  '/humor': typeof HumorRoute
  '/momentos': typeof MomentosRoute
  '/quiz': typeof QuizRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cartas': typeof CartasRoute
  '/clube-do-livro': typeof ClubeDoLivroRoute
  '/dates': typeof DatesRoute
  '/filmes': typeof FilmesRoute
  '/humor': typeof HumorRoute
  '/momentos': typeof MomentosRoute
  '/quiz': typeof QuizRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cartas': typeof CartasRoute
  '/clube-do-livro': typeof ClubeDoLivroRoute
  '/dates': typeof DatesRoute
  '/filmes': typeof FilmesRoute
  '/humor': typeof HumorRoute
  '/momentos': typeof MomentosRoute
  '/quiz': typeof QuizRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cartas'
    | '/clube-do-livro'
    | '/dates'
    | '/filmes'
    | '/humor'
    | '/momentos'
    | '/quiz'
    | '/wishlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cartas'
    | '/clube-do-livro'
    | '/dates'
    | '/filmes'
    | '/humor'
    | '/momentos'
    | '/quiz'
    | '/wishlist'
  id:
    | '__root__'
    | '/'
    | '/cartas'
    | '/clube-do-livro'
    | '/dates'
    | '/filmes'
    | '/humor'
    | '/momentos'
    | '/quiz'
    | '/wishlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartasRoute: typeof CartasRoute
  ClubeDoLivroRoute: typeof ClubeDoLivroRoute
  DatesRoute: typeof DatesRoute
  FilmesRoute: typeof FilmesRoute
  HumorRoute: typeof HumorRoute
  MomentosRoute: typeof MomentosRoute
  QuizRoute: typeof QuizRoute
  WishlistRoute: typeof WishlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/momentos': {
      id: '/momentos'
      path: '/momentos'
      fullPath: '/momentos'
      preLoaderRoute: typeof MomentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/humor': {
      id: '/humor'
      path: '/humor'
      fullPath: '/humor'
      preLoaderRoute: typeof HumorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filmes': {
      id: '/filmes'
      path: '/filmes'
      fullPath: '/filmes'
      preLoaderRoute: typeof FilmesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dates': {
      id: '/dates'
      path: '/dates'
      fullPath: '/dates'
      preLoaderRoute: typeof DatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube-do-livro': {
      id: '/clube-do-livro'
      path: '/clube-do-livro'
      fullPath: '/clube-do-livro'
      preLoaderRoute: typeof ClubeDoLivroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartas': {
      id: '/cartas'
      path: '/cartas'
      fullPath: '/cartas'
      preLoaderRoute: typeof CartasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartasRoute: CartasRoute,
  ClubeDoLivroRoute: ClubeDoLivroRoute,
  DatesRoute: DatesRoute,
  FilmesRoute: FilmesRoute,
  HumorRoute: HumorRoute,
  MomentosRoute: MomentosRoute,
  QuizRoute: QuizRoute,
  WishlistRoute: WishlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
